server:
  port: 8088

spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  messages:
    basename: messages
  jackson:
    serialization:
      indent-output: true
  datasource:
    url: jdbc:mysql://localhost:3306/kcc
    username: root
    password: dlatl#00
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 5
      connection-timeout: 600000
management:
  endpoints:
    web:
      exposure:
        include: "*"
############################################################################
# Log properties
logging:
  file:
    name: ${app.home}/api-server.log
  config: "classpath:logback-spring.xml"
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %X{MDC.REQUEST_ID} %-15logger{0} - %msg%n%rEx{full,
                Java.lang.reflect.Method,
                org.apache.catalina,
                org.springframework.aop,
                org.springframework.security,
                org.springframework.transaction,
                org.springframework.web,
                org.springframework.test,
                org.springframework.mock,
                org.junit,
                sun.reflect,
                net.sf.cglib,
                CGLIB,
                java.lang.Thread,
                java.util.concurrent,
                org.apache.coyote,
                org.apache.tomcat,
                javax.servlet.http.HttpServlet
                com.zaxxer.hikari.pool
                }"
    file: "%d{HH:mm:ss.SSS} %-5level %X{MDC.REQUEST_ID} %-15logger{0} - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz"
      max-file-size: 100MB
      max-history: 365


############################################################################
# Mybatis propperties
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  check-config-location: true
  mapper-locations : classpath*:mapper/**/*.xml

############################################################################
# Pagehelper propperties
pagehelper:
  helperDialect: MysqlSQL
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql